owner: Bitris-Ai
repo: status

# Only monitor public-facing Bitris services
sites:
  - name: Bitris AI Platform
    url: https://www.bitris.ai/api/status
    maxResponseTime: 5000
  - name: Voice Services
    url: https://www.bitris.ai/api/voice/status
    maxResponseTime: 5000

status-website:
  cname: status.bitris.ai
  name: Bitris AI
  introTitle: "System Status"
  introMessage: "Real-time operational monitoring for all Bitris AI services"
  logoUrl: https://raw.githubusercontent.com/Bitris-Ai/status/master/assets/bitris-logo.svg
  faviconSvg: https://raw.githubusercontent.com/Bitris-Ai/status/master/assets/bitris-icon.svg
  themeUrl: https://raw.githubusercontent.com/Bitris-Ai/status/master/assets/theme.css?v=2
  js: https://raw.githubusercontent.com/Bitris-Ai/status/master/assets/custom.js
  navbar:
    - title: Home
      href: https://www.bitris.ai
    - title: Support
      href: https://www.bitris.ai/support
  i18n:
    footer: "© 2025 Bitris AI - All systems monitored in real-time"
    url: ""
    status: ""
    history: ""
    link: ""

# Monitoring schedule
workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "0 */6 * * *"
  graphs: "0 0 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"

# No public assignees
assignees: []

skipHomepage: true
skipDescriptionForNotification: true

user-agent: Bitris-Status-Monitor

commitMessages:
  readmeContent: ":pencil: Update status summary [skip ci]"
  statusChange: "$SITE_NAME is $STATUS ($RESPONSE_CODE)"
  commitAuthorName: "Bitris Status Bot"
  commitAuthorEmail: "status@bitris.ai"
